version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m    # Biar hemat RAM
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 1g   # optional, bisa dihapus kalau gak pakai Docker Swarm

  fastapi-app:
    build:
      context: ./app
    ports:
      - "9001:9001"
    depends_on:
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  esdata:
